/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: android-arm64"
#define DATE "built on: Sun Feb 16 07:30:12 2020 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6',
    '4','-','l','i','n','u','x','-','a','n','d','r','o','i','d','-',
    'g','c','c',' ','-','f','P','I','C',' ','-','p','t','h','r','e',
    'a','d',' ',' ','-','m','a','n','d','r','o','i','d',' ','-','-',
    's','y','s','r','o','o','t','=','/','U','s','e','r','s','/','t',
    'i','a','n','p','e','n','g','/','t','o','o','l','s','/','a','n',
    'd','r','o','i','d','-','n','d','k','-','r','1','4','b','/','p',
    'l','a','t','f','o','r','m','s','/','a','n','d','r','o','i','d',
    '-','2','4','/','a','r','c','h','-','a','r','m','6','4',' ','-',
    'W','a',',','-','-','n','o','e','x','e','c','s','t','a','c','k',
    ' ','-','W','a','l','l',' ','-','O','3',' ','-','D','O','P','E',
    'N','S','S','L','_','U','S','E','_','N','O','D','E','L','E','T',
    'E',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',' ',
    '-','D','O','P','E','N','S','S','L','_','C','P','U','I','D','_',
    'O','B','J',' ','-','D','O','P','E','N','S','S','L','_','B','N',
    '_','A','S','M','_','M','O','N','T',' ','-','D','S','H','A','1',
    '_','A','S','M',' ','-','D','S','H','A','2','5','6','_','A','S',
    'M',' ','-','D','S','H','A','5','1','2','_','A','S','M',' ','-',
    'D','K','E','C','C','A','K','1','6','0','0','_','A','S','M',' ',
    '-','D','V','P','A','E','S','_','A','S','M',' ','-','D','E','C',
    'P','_','N','I','S','T','Z','2','5','6','_','A','S','M',' ','-',
    'D','P','O','L','Y','1','3','0','5','_','A','S','M',' ','-','D',
    'N','D','E','B','U','G',' ','-','D','_','_','A','N','D','R','O',
    'I','D','_','A','P','I','_','_','=','2','4','\0'
};
